version: '3.9'

# services
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGO_DB_URI: mongodb://mongo_db:27017/testdb
      SECRET: mysecret
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
